### ISSUE TITLE
Implement custom ship dimensions

### ISSUE THREAD

**Issue by fs-c** [fs-c/vt-space#7]
`struct ship` has `width` and `height` properties but `draw_ship()` does not scale the wings or snout properly (or at all).

The drawn ship should fit _inside_ the given dimensions, whereas in the current implementation a rectangle with the given width and height is drawn and other ship 'parts' are added to the sides and top of it.

**Comment by LW2904** [comment]
After toying around with a number of ways on how this could be solved, I eventually came to the conclusion that it's not worth the decrease in performance that the calculations needed for this would cause.

`draw_ship()` has, as a consequence, been renamed to `draw_player()`, and will only draw a nice looking ship if the dimension properties are what it expects them to be.
